name: Build AmneziaWG Modules

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "amneziawg-kmod for rockchip/armv8"
    env:
      TAG: "23.05.5"
      PKGARCH: "aarch64_cortex-a53"
      TARGET: "rockchip"
      SUBTARGET: "armv8"
      VERMAGIC: "0919bf77bd78281b8293e21504faecfb"

    steps:
      - name: Checkout OpenWRT
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v23.05.5
          fetch-depth: 1

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget nodejs npm

      - name: Clone AmneziaWG
        run: |
          git clone https://github.com/Slava-Shchipunov/awg-openwrt.git awg
          cp -r awg/amneziawg package/

      - name: Configure and Build
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=m" >> .config
          make defconfig
          make package/kmod-amneziawg/compile -j$(nproc) V=s

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amneziawg-ipks
          path: |
            bin/packages/*/*/kmod-amneziawg*.ipk
            bin/packages/*/*/amneziawg-tools*.ipk
